#!/bin/sh

case $1 in
	hide_include)
		exit 0 # hide, install
	;;
	hide_exclude)
		exit 1 # hide, do not install
	;;
	show_include)
		exit 2 # show, install
	;;
	show_exclude)
		exit 3 # show, do not install
	;;
	*)
		exit 3
	;;
esac
