#!/bin/sh

case $1 in
	hide-include|0)
		exit 0 # hide, install
	;;
	hide-exclude|1)
		exit 1 # hide, do not install
	;;
	show-include|2)
		exit 2 # show, install
	;;
	show-exclude|3)
		exit 3 # show, do not install
	;;
	*)
		exit 3
	;;
esac
